/*
 *    Copyright 2015 United States Government as represented by NASA
 *       Marshall Space Flight Center. All Rights Reserved.
 *
 *    Released under the NASA Open Source Software Agreement version 1.3;
 *    You may obtain a copy of the Agreement at:
 * 
 *        http://ti.arc.nasa.gov/opensource/nosa/
 * 
 *    The subject software is provided "AS IS" WITHOUT ANY WARRANTY of any kind,
 *    either expressed, implied or statutory and this agreement does not,
 *    in any manner, constitute an endorsement by government agency of any
 *    results, designs or products resulting from use of the subject software.
 *    See the Agreement for the specific language governing permissions and
 *    limitations.
 */

package udprepeater;

public class UdpRptrUiMainFrame extends javax.swing.JFrame
{
  
  /** Creates new form EsmUiMainFrame */
  public UdpRptrUiMainFrame()
  {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel_mainWindowCenterPanel = new javax.swing.JPanel();
    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane_string = new javax.swing.JScrollPane();
    jPanel_mainPanel = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextField_inputIpAddress = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextField_inputPort = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jTextField_outputIpAddress = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    jTextField_transmitToPort = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jLabel_totalPacktes = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel_pktsPerSec = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel_kbitsPerSec = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel_maxPktsPerSec = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    jLabel_seqCtr = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel_minPktLen = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel_maxPktLen = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jButton_capturePkt = new javax.swing.JButton();
    jButton_StartFileCapture = new javax.swing.JButton();
    jTextField_filename = new javax.swing.JTextField();
    jButton_StopFileCapture = new javax.swing.JButton();
    jPanel8 = new javax.swing.JPanel();
    jCheckBox_addSeqCtr = new javax.swing.JCheckBox();
    jLabel12 = new javax.swing.JLabel();
    jTextField_totalPktsToGen = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jButton_resetSeqCtr1 = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jButton_startCaptureOnly = new javax.swing.JButton();
    jButton_start = new javax.swing.JButton();
    jButton_stop = new javax.swing.JButton();
    jPanel9 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jTextField_payloadLength = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    jTextField_genRate = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    jButton_startGenerating = new javax.swing.JButton();
    jButton_stopGenerating = new javax.swing.JButton();
    jScrollPane_messages = new javax.swing.JScrollPane();
    jList_messages = new javax.swing.JList();
    jPanel_statusBar = new javax.swing.JPanel();
    jLabel_statusBar = new javax.swing.JLabel();
    jMenuBar_mainFrame = new javax.swing.JMenuBar();
    jMenu_fileMenu = new javax.swing.JMenu();
    jMenuItem_fileExit = new javax.swing.JMenuItem();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem_copyToClipboard = new javax.swing.JMenuItem();

    setTitle("UDP Repeater");
    setName("jFrame_mainWindow"); // NOI18N
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    jPanel_mainWindowCenterPanel.setLayout(new java.awt.BorderLayout());

    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    jSplitPane1.setResizeWeight(0.9);
    jSplitPane1.setDoubleBuffered(true);
    jSplitPane1.setOneTouchExpandable(true);

    jScrollPane_string.setDoubleBuffered(true);
    jScrollPane_string.setMinimumSize(new java.awt.Dimension(790, 290));
    jScrollPane_string.setPreferredSize(new java.awt.Dimension(790, 290));

    jPanel_mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
    jPanel_mainPanel.setLayout(new javax.swing.BoxLayout(jPanel_mainPanel, javax.swing.BoxLayout.Y_AXIS));

    jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
    jPanel1.setMinimumSize(new java.awt.Dimension(293, 30));

    jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel1.setText("UDP Input:  IP Address:");
    jPanel1.add(jLabel1);

    jTextField_inputIpAddress.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_inputIpAddress.setText("239.9.9.9");
    jTextField_inputIpAddress.setName("InputIPAddress"); // NOI18N
    jTextField_inputIpAddress.setPreferredSize(new java.awt.Dimension(150, 20));
    jPanel1.add(jTextField_inputIpAddress);

    jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel2.setText("   Port: ");
    jPanel1.add(jLabel2);

    jTextField_inputPort.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_inputPort.setText("30000");
    jTextField_inputPort.setName("InputPort"); // NOI18N
    jTextField_inputPort.setPreferredSize(new java.awt.Dimension(80, 20));
    jPanel1.add(jTextField_inputPort);

    jPanel_mainPanel.add(jPanel1);

    jPanel2.setMaximumSize(new java.awt.Dimension(32767, 30));
    jPanel2.setMinimumSize(new java.awt.Dimension(293, 30));

    jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel3.setText("UDP Output: IP Address:");
    jPanel2.add(jLabel3);

    jTextField_outputIpAddress.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_outputIpAddress.setText("127.0.0.1");
    jTextField_outputIpAddress.setName("OutputIPAddress"); // NOI18N
    jTextField_outputIpAddress.setPreferredSize(new java.awt.Dimension(150, 20));
    jTextField_outputIpAddress.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_outputIpAddressActionPerformed(evt);
      }
    });
    jPanel2.add(jTextField_outputIpAddress);

    jLabel17.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel17.setText("   Port: ");
    jPanel2.add(jLabel17);

    jTextField_transmitToPort.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_transmitToPort.setText("33442");
    jTextField_transmitToPort.setName("OutputPort"); // NOI18N
    jTextField_transmitToPort.setPreferredSize(new java.awt.Dimension(80, 20));
    jPanel2.add(jTextField_transmitToPort);

    jPanel_mainPanel.add(jPanel2);

    jPanel4.setMaximumSize(new java.awt.Dimension(32767, 30));

    jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel5.setText("Total Packets:");
    jPanel4.add(jLabel5);

    jLabel_totalPacktes.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_totalPacktes.setText("0");
    jPanel4.add(jLabel_totalPacktes);

    jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel6.setText("   Pkts/sec: ");
    jPanel4.add(jLabel6);

    jLabel_pktsPerSec.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_pktsPerSec.setText("0");
    jPanel4.add(jLabel_pktsPerSec);

    jLabel9.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel9.setText("   Rate: ");
    jPanel4.add(jLabel9);

    jLabel_kbitsPerSec.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_kbitsPerSec.setText("0");
    jPanel4.add(jLabel_kbitsPerSec);

    jLabel16.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel16.setText("   Max Pkts/sec: ");
    jPanel4.add(jLabel16);

    jLabel_maxPktsPerSec.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_maxPktsPerSec.setText("0");
    jPanel4.add(jLabel_maxPktsPerSec);

    jPanel_mainPanel.add(jPanel4);

    jPanel5.setMaximumSize(new java.awt.Dimension(32767, 30));

    jLabel13.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel13.setText("Seq Ctr:");
    jPanel5.add(jLabel13);

    jLabel_seqCtr.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_seqCtr.setText("0");
    jPanel5.add(jLabel_seqCtr);

    jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel7.setText("   Min Pkt Len:");
    jPanel5.add(jLabel7);

    jLabel_minPktLen.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_minPktLen.setText("0");
    jPanel5.add(jLabel_minPktLen);

    jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel8.setText("   Max Pkt Len: ");
    jPanel5.add(jLabel8);

    jLabel_maxPktLen.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel_maxPktLen.setText("0");
    jPanel5.add(jLabel_maxPktLen);

    jPanel_mainPanel.add(jPanel5);

    jPanel3.setMaximumSize(new java.awt.Dimension(32767, 40));
    jPanel3.setMinimumSize(new java.awt.Dimension(521, 40));
    jPanel3.setPreferredSize(new java.awt.Dimension(521, 40));
    jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));

    jButton_capturePkt.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_capturePkt.setText("Capture Pkt");
    jButton_capturePkt.setActionCommand("capturePkt");
    jPanel3.add(jButton_capturePkt);

    jButton_StartFileCapture.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_StartFileCapture.setText("Start File Capture");
    jButton_StartFileCapture.setActionCommand("startFileCapture");
    jPanel3.add(jButton_StartFileCapture);

    jTextField_filename.setText("C:\\z\\videocap.mp4");
    jTextField_filename.setName("FileCaptureName"); // NOI18N
    jTextField_filename.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel3.add(jTextField_filename);

    jButton_StopFileCapture.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_StopFileCapture.setText("Stop File Capture");
    jButton_StopFileCapture.setActionCommand("stopFileCapture");
    jPanel3.add(jButton_StopFileCapture);

    jPanel_mainPanel.add(jPanel3);

    jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
    jPanel8.setMaximumSize(new java.awt.Dimension(32767, 40));
    jPanel8.setMinimumSize(new java.awt.Dimension(182, 40));
    jPanel8.setPreferredSize(new java.awt.Dimension(256, 40));

    jCheckBox_addSeqCtr.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
    jCheckBox_addSeqCtr.setSelected(true);
    jCheckBox_addSeqCtr.setText("Append 10 Char Seq Ctr:");
    jCheckBox_addSeqCtr.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    jCheckBox_addSeqCtr.setName("AddSeqCtr2"); // NOI18N
    jPanel8.add(jCheckBox_addSeqCtr);

    jLabel12.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel12.setText(" Num Pkts:");
    jLabel12.setToolTipText("0 = continuous");
    jPanel8.add(jLabel12);

    jTextField_totalPktsToGen.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_totalPktsToGen.setText("864000");
    jTextField_totalPktsToGen.setToolTipText("0 = continuous");
    jTextField_totalPktsToGen.setMaximumSize(new java.awt.Dimension(80, 2147483647));
    jTextField_totalPktsToGen.setMinimumSize(new java.awt.Dimension(80, 26));
    jTextField_totalPktsToGen.setName("GenTotalPkts"); // NOI18N
    jTextField_totalPktsToGen.setPreferredSize(new java.awt.Dimension(80, 20));
    jPanel8.add(jTextField_totalPktsToGen);

    jLabel15.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel15.setText("    ");
    jPanel8.add(jLabel15);

    jButton_resetSeqCtr1.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_resetSeqCtr1.setText("Reset Seq Ctr");
    jButton_resetSeqCtr1.setActionCommand("resetSeqCtr");
    jPanel8.add(jButton_resetSeqCtr1);

    jPanel_mainPanel.add(jPanel8);

    jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
    jPanel6.setMaximumSize(new java.awt.Dimension(32767, 40));
    jPanel6.setMinimumSize(new java.awt.Dimension(505, 40));
    jPanel6.setPreferredSize(new java.awt.Dimension(505, 40));
    jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));

    jButton_startCaptureOnly.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_startCaptureOnly.setText("Start Capturing");
    jButton_startCaptureOnly.setActionCommand("captureonly");
    jPanel6.add(jButton_startCaptureOnly);

    jButton_start.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_start.setText("Start Capturing & Forwarding");
    jButton_start.setActionCommand("start");
    jPanel6.add(jButton_start);

    jButton_stop.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_stop.setText("Stop");
    jButton_stop.setActionCommand("stop");
    jPanel6.add(jButton_stop);

    jPanel_mainPanel.add(jPanel6);

    jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
    jPanel9.setMaximumSize(new java.awt.Dimension(32767, 40));
    jPanel9.setMinimumSize(new java.awt.Dimension(365, 40));
    jPanel9.setPreferredSize(new java.awt.Dimension(365, 40));

    jLabel10.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel10.setText(" Payload Length:");
    jPanel9.add(jLabel10);

    jTextField_payloadLength.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_payloadLength.setText("1316");
    jTextField_payloadLength.setMaximumSize(new java.awt.Dimension(60, 2147483647));
    jTextField_payloadLength.setMinimumSize(new java.awt.Dimension(60, 26));
    jTextField_payloadLength.setName("GenPayloadLen"); // NOI18N
    jTextField_payloadLength.setPreferredSize(new java.awt.Dimension(60, 20));
    jTextField_payloadLength.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_payloadLengthActionPerformed(evt);
      }
    });
    jPanel9.add(jTextField_payloadLength);

    jLabel11.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel11.setText(" Rate (Pkts/s):");
    jPanel9.add(jLabel11);

    jTextField_genRate.setFont(new java.awt.Font("Monospaced", 1, 14));
    jTextField_genRate.setText("160");
    jTextField_genRate.setMaximumSize(new java.awt.Dimension(60, 2147483647));
    jTextField_genRate.setMinimumSize(new java.awt.Dimension(60, 26));
    jTextField_genRate.setName("GenPktRate"); // NOI18N
    jTextField_genRate.setPreferredSize(new java.awt.Dimension(60, 20));
    jTextField_genRate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_genRateActionPerformed(evt);
      }
    });
    jPanel9.add(jTextField_genRate);

    jLabel14.setFont(new java.awt.Font("Monospaced", 1, 14));
    jLabel14.setText("    ");
    jPanel9.add(jLabel14);

    jButton_startGenerating.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_startGenerating.setText("Start Generating");
    jButton_startGenerating.setActionCommand("startGenerating");
    jPanel9.add(jButton_startGenerating);

    jButton_stopGenerating.setFont(new java.awt.Font("Monospaced", 1, 14));
    jButton_stopGenerating.setText("Stop");
    jButton_stopGenerating.setActionCommand("stopGenerating");
    jPanel9.add(jButton_stopGenerating);

    jPanel_mainPanel.add(jPanel9);

    jScrollPane_string.setViewportView(jPanel_mainPanel);

    jSplitPane1.setTopComponent(jScrollPane_string);

    jScrollPane_messages.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane_messages.setDoubleBuffered(true);
    jScrollPane_messages.setMinimumSize(new java.awt.Dimension(22, 60));
    jScrollPane_messages.setPreferredSize(new java.awt.Dimension(722, 60));

    jList_messages.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane_messages.setViewportView(jList_messages);

    jSplitPane1.setBottomComponent(jScrollPane_messages);

    jPanel_mainWindowCenterPanel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel_mainWindowCenterPanel, java.awt.BorderLayout.CENTER);

    jPanel_statusBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

    jLabel_statusBar.setText("    ");
    jPanel_statusBar.add(jLabel_statusBar);

    getContentPane().add(jPanel_statusBar, java.awt.BorderLayout.SOUTH);

    jMenu_fileMenu.setText("File");
    jMenu_fileMenu.setFont(new java.awt.Font("Monospaced", 1, 12));

    jMenuItem_fileExit.setFont(new java.awt.Font("Monospaced", 1, 12));
    jMenuItem_fileExit.setText("Exit");
    jMenuItem_fileExit.setActionCommand("exit");
    jMenu_fileMenu.add(jMenuItem_fileExit);

    jMenuBar_mainFrame.add(jMenu_fileMenu);

    jMenu1.setText("Edit");
    jMenu1.setFont(new java.awt.Font("Monospaced", 1, 12));

    jMenuItem_copyToClipboard.setFont(new java.awt.Font("Monospaced", 1, 12));
    jMenuItem_copyToClipboard.setText("Copy Msgs to Clipboard");
    jMenuItem_copyToClipboard.setActionCommand("copytoclipboard");
    jMenu1.add(jMenuItem_copyToClipboard);

    jMenuBar_mainFrame.add(jMenu1);

    setJMenuBar(jMenuBar_mainFrame);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt)
  {//GEN-FIRST:event_exitForm
    System.out.println ("EsmUiMainFrame.exitForm : windowClosing event needs " +
      "to be overridden by the controller - please take corrective action" );
    System.out.flush();
  }//GEN-LAST:event_exitForm

private void jTextField_outputIpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_outputIpAddressActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField_outputIpAddressActionPerformed

private void jTextField_payloadLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_payloadLengthActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField_payloadLengthActionPerformed

private void jTextField_genRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_genRateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField_genRateActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JButton jButton_StartFileCapture;
  javax.swing.JButton jButton_StopFileCapture;
  javax.swing.JButton jButton_capturePkt;
  javax.swing.JButton jButton_resetSeqCtr1;
  javax.swing.JButton jButton_start;
  javax.swing.JButton jButton_startCaptureOnly;
  javax.swing.JButton jButton_startGenerating;
  javax.swing.JButton jButton_stop;
  javax.swing.JButton jButton_stopGenerating;
  javax.swing.JCheckBox jCheckBox_addSeqCtr;
  javax.swing.JLabel jLabel1;
  javax.swing.JLabel jLabel10;
  javax.swing.JLabel jLabel11;
  javax.swing.JLabel jLabel12;
  javax.swing.JLabel jLabel13;
  javax.swing.JLabel jLabel14;
  javax.swing.JLabel jLabel15;
  javax.swing.JLabel jLabel16;
  javax.swing.JLabel jLabel17;
  javax.swing.JLabel jLabel2;
  javax.swing.JLabel jLabel3;
  javax.swing.JLabel jLabel5;
  javax.swing.JLabel jLabel6;
  javax.swing.JLabel jLabel7;
  javax.swing.JLabel jLabel8;
  javax.swing.JLabel jLabel9;
  javax.swing.JLabel jLabel_kbitsPerSec;
  javax.swing.JLabel jLabel_maxPktLen;
  javax.swing.JLabel jLabel_maxPktsPerSec;
  javax.swing.JLabel jLabel_minPktLen;
  javax.swing.JLabel jLabel_pktsPerSec;
  javax.swing.JLabel jLabel_seqCtr;
  javax.swing.JLabel jLabel_statusBar;
  javax.swing.JLabel jLabel_totalPacktes;
  javax.swing.JList jList_messages;
  javax.swing.JMenu jMenu1;
  javax.swing.JMenuBar jMenuBar_mainFrame;
  javax.swing.JMenuItem jMenuItem_copyToClipboard;
  javax.swing.JMenuItem jMenuItem_fileExit;
  javax.swing.JMenu jMenu_fileMenu;
  javax.swing.JPanel jPanel1;
  javax.swing.JPanel jPanel2;
  javax.swing.JPanel jPanel3;
  javax.swing.JPanel jPanel4;
  javax.swing.JPanel jPanel5;
  javax.swing.JPanel jPanel6;
  javax.swing.JPanel jPanel8;
  javax.swing.JPanel jPanel9;
  javax.swing.JPanel jPanel_mainPanel;
  javax.swing.JPanel jPanel_mainWindowCenterPanel;
  javax.swing.JPanel jPanel_statusBar;
  javax.swing.JScrollPane jScrollPane_messages;
  javax.swing.JScrollPane jScrollPane_string;
  javax.swing.JSplitPane jSplitPane1;
  javax.swing.JTextField jTextField_filename;
  javax.swing.JTextField jTextField_genRate;
  javax.swing.JTextField jTextField_inputIpAddress;
  javax.swing.JTextField jTextField_inputPort;
  javax.swing.JTextField jTextField_outputIpAddress;
  javax.swing.JTextField jTextField_payloadLength;
  javax.swing.JTextField jTextField_totalPktsToGen;
  javax.swing.JTextField jTextField_transmitToPort;
  // End of variables declaration//GEN-END:variables
  
}
