/*
 *    Copyright 2006 Intel Corporation
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

#ifndef _API_BLOCK_PROCESSOR_H_
#define _API_BLOCK_PROCESSOR_H_

#include <oasys/util/Singleton.h>

#include "BlockProcessor.h"

namespace dtn {

/**
 * Block processor implementation for any bundle block generated by the API.
 */
class APIBlockProcessor : public BlockProcessor,
                          public oasys::Singleton<APIBlockProcessor> {
public:
    /// Constructor
    APIBlockProcessor();
    
    /// @{ Virtual from BlockProcessor
    int64_t consume(Bundle* bundle, BlockInfo* block, u_char* buf, size_t len);
    int generate(const Bundle* bundle, BlockInfoVec* xmit_blocks,
                  BlockInfo* block, const LinkRef& link, bool last);
    /// @}
};

} // namespace dtn

#endif /* _API_BLOCK_PROCESSOR_H_ */
